service: image-resizer-lambda
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  memorySize: 256
  environment:
    BUCKET_NAME: ${self:custom.Bucket.name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.Bucket.name}"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${self:custom.Bucket.name}/*"

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /save
          method: get
      - s3:
          bucket: ${self:custom.Bucket.name}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
            - suffix: .jpg

custom:
  Bucket:
    name: zen-store
